---
- name: Configure instance
  hosts: all
  tags: ['core-instance']
  become: yes
  vars_files:
  - credentials.yml
  roles:
  - ansible-role-lxde-install
  - ansible-role-vnc-install
  - ansible-role-nginx-install
  - ansible-role-nginx-ssl-selfsigned
  - ansible-role-novnc-install
  - { role: ansible-osbot, tags:['client'] }

