---
- name: Configure instance
  hosts: all
  become: yes
  vars_files:
  - credentials.yml

  roles:
  - { role: ansible-role-lxde-install, notify: "Start Supervisor" }
  - { role: ansible-role-vnc-install, notify: "Start Supervisor" }
  - { role: ansible-role-nginx-install, notify: "Start Nginx" }
  - role: ansible-role-nginx-ssl-selfsigned
  - { role: ansible-role-novnc-install, notify: "Start Supervisor" }

  tasks:
  - name: Add apt-get repository
    apt_repository:
      repo: 'ppa:openjdk-r/ppa'

  - name: Install Java
    apt:
      name: openjdk-8-jdk
      state: present

  - name: Prepare download folder
    become: no
    file:
      path: ~/Downloads
      state: directory

  - name: Download client
    become: no
    get_url:
      dest: ~/Downloads/osbot.jar
      url: https://osbot.org/mvc/get
    notify:
    - "Run client"

  - name: Run client
    become: no
    shell: java -jar ~/Downloads/osbot.jar
