---
- name: Configure instance
  hosts: all
  tags: ['core-instance']
  become: yes
  vars_files:
  - credentials.yml
  roles:
  - ansible-role-lxde-install
  - ansible-role-vnc-install
  - ansible-role-nginx-install
  - ansible-role-nginx-ssl-selfsigned
  - ansible-role-novnc-install

- name: Configure client
  hosts: all
  tags: ['client']
  become: yes
  vars_files:
  - credentials.yml
  tasks:
  - name: Add apt-get repository
    apt_repository:
      repo: 'ppa:openjdk-r/ppa'

  - name: Install Java
    apt:
      name: openjdk-8-jdk
      state: present

  - name: Prepare download folder
    become: no
    file:
      path: ~/Downloads
      state: directory

  - name: Download client
    become: no
    get_url:
      dest: ~/Downloads/osbot.jar
      url: https://osbot.org/mvc/get

  - name: Run client
    become: no
    shell: java -jar ~/Downloads/osbot.jar
    environment:
      DISPLAY: ':1'
    async: 0
    poll: 0
