- name: Create Instance
  hosts: localhost
  connection: local
  vars_files:
  - credentials.yml
  vars:
    machine_type: n1-standard-1
    image: ubuntu-1404
    zone: us-east1-c
    host_prefix: bot
  tasks:
  - name: Install GCE Dependencies
    pip:
      name: "{{ item }}"
      state: present
    with_items:
    - apache-libcloud

  - name: Launch instance
    gce:
      instance_names: "{{ host_prefix }}{{ item }}"
      machine_type: "{{ machine_type }}"
      image: "{{ image }}"
      service_account_email: "{{ service_account_email }}"
      project_id: "{{ project_id }}"
      credentials_file: '{{ credentials_file }}'
      zone: "{{ zone }}"
      tags: ["https-server"]
      state: present
    register: gce
    with_sequence: start={{ start | default(1) }} end={{ end | default(1) }}

  - name: Report GCE
    debug:
      var: gce
