---
- src: https://github.com/carlosfrias/ansible-role-nginx-ssl-selfsigned.git
- src: https://github.com/carlosfrias/ansible-role-lxde-install.git
- src: https://github.com/carlosfrias/ansible-role-vnc-install.git
- src: https://github.com/carlosfrias/ansible-role-novnc-install.git
- src: https://github.com/carlosfrias/ansible-role-nginx-install.git
